
#MySQL Settings --- REQUIRED ---
#Stores player time, last server, etc
mysql:
  host: localhost
  port: 3306
  username: root
  password: password
  database: bungeeplayer
  tablePrefix: 'bplayer_'

hidden:
  - some-player-name

settings:
  ignore-port: false
  ignore-numbers: false
